export default {
	navigation: {
		bg: require('../../../assets/marketplace/navigation-bg.png'),
		logo: require('../../../assets/marketplace/flag.png'),
	},
	mint: {
		keyVisual: require('../../../assets/mint/key-visual.png'),
		cards: require('../../../assets/mint/cards.png'),
	},
	marketplace: {
		headingBackground: require('../../../assets/marketplace/heading-background.png'),
		mainBackground: require('../../../assets/marketplace/main-background.png'),
		underRealmButton: {
			normal: {
				left: require('../../../assets/marketplace/under-realm-normal-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-normal-middle.png'),
				right: require('../../../assets/marketplace/under-realm-normal-right-edge.png'),
			},
			hover: {
				left: require('../../../assets/marketplace/under-realm-hover-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-hover-middle.png'),
				right: require('../../../assets/marketplace/under-realm-hover-right-edge.png'),
			},
		},
		underRealmSubButton: {
			normal: {
				left: require('../../../assets/marketplace/under-realm-sub-normal-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-sub-normal-middle.png'),
				right: require('../../../assets/marketplace/under-realm-sub-normal-right-edge.png'),
			},
			hover: {
				left: require('../../../assets/marketplace/under-realm-sub-hover-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-sub-hover-middle.png'),
				right: require('../../../assets/marketplace/under-realm-sub-hover-right-edge.png'),
			},
		},
		card: {
			back: require('../../../assets/marketplace/under-realm-card-back.png'),
			front: require('../../../assets/marketplace/under-realm-card-front.png'),
		},
		mintBanner: require('../../../assets/marketplace/mint-banner.png'),
		coinUsd: require('../../../assets/marketplace/coin-usd.png'),
		mintWhyBuyNft: {
			edgeTopLeft: require('../../../assets/marketplace/mint-top-left-edge.png'),
			edgeTopRight: require('../../../assets/marketplace/mint-top-right-edge.png'),
			edgeBottomLeft: require('../../../assets/marketplace/mint-bottom-left-edge.png'),
			edgeBottomRight: require('../../../assets/marketplace/mint-bottom-right-edge.png'),
			borderTop: require('../../../assets/marketplace/mint-top-border.png'),
			borderBottom: require('../../../assets/marketplace/mint-bottom-border.png'),
			borderLeft: require('../../../assets/marketplace/mint-left-border.png'),
			borderRight: require('../../../assets/marketplace/mint-right-border.png'),
			background: require('../../../assets/marketplace/mint-bg.png'),
			bloodDrop: require('../../../assets/marketplace/icon-blood-drop.png'),
			patternTopLeft: require('../../../assets/marketplace/mint-top-left-pattern.png'),
			patternTopRight: require('../../../assets/marketplace/mint-top-right-pattern.png'),
			patternBottomLeft: require('../../../assets/marketplace/mint-bottom-left-pattern.png'),
			patternBottomRight: require('../../../assets/marketplace/mint-bottom-right-pattern.png'),
		},
		faq: {
			top: require('../../../assets/marketplace/faq-top.png'),
			middle: require('../../../assets/marketplace/faq-middle.png'),
			bottom: require('../../../assets/marketplace/faq-bottom.png'),
		},
		chevronDown: require('../../../assets/marketplace/chevron-down.png'),
		titleSeparator: require('../../../assets/marketplace/title-separator.png'),
		buyButtonBackground: require('../../../assets/marketplace/buy-button-bg.png'),
		buyButtonDash: require('../../../assets/marketplace/buy-button-inner-dash.png'),
		popupBorder: require('../../../assets/marketplace/popup-border.png'),
		popupBackground: require('../../../assets/marketplace/popup-bg.png'),
	},
	home: {
		headingBackground: require('../../../assets/home/heading-background.png'),
		cardsImage: require('../../../assets/home/cards-image.png'),
		battlefieldBackground: require('../../../assets/home/battlefield-background.png'),
		cardExplainBackground: require('../../../assets/home/card-explain-background.png'),
		cardExplain: require('../../../assets/home/card-explain.png'),
		elementalInteractionFirstBackground: require('../../../assets/home/elemental-interaction-first-background.png'),
		elementalInteractionSecondBackground: require('../../../assets/home/elemental-interaction-second-background.png'),
		elementalInteractionVisual: require('../../../assets/home/elemental-interaction-visual.png'),
		cardTypesBackground: require('../../../assets/home/card-type-background.png'),
		cardTypesSpellVisual: require('../../../assets/home/card-type-spell-visual.png'),
		classes: {
			background: require('../../../assets/home/classes/background.png'),
			logoBackground: require('../../../assets/home/classes/logo-background.png'),
			borderBackground: require('../../../assets/home/classes/border-background.png'),
			classContentBackground: require('../../../assets/home/classes/class-content-background.png'),
			summoner: {
				backgroundActive: require('../../../assets/home/classes/summoner/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/summoner/logo-background-active.png'),
				logo: require('../../../assets/home/classes/summoner/logo.png'),
				logoActive: require('../../../assets/home/classes/summoner/logo-active.png'),
			},
			assassin: {
				backgroundActive: require('../../../assets/home/classes/assassin/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/assassin/logo-background-active.png'),
				logo: require('../../../assets/home/classes/assassin/logo.png'),
				logoActive: require('../../../assets/home/classes/assassin/logo-active.png'),
			},
			wizard: {
				backgroundActive: require('../../../assets/home/classes/wizard/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/wizard/logo-background-active.png'),
				logo: require('../../../assets/home/classes/wizard/logo.png'),
				logoActive: require('../../../assets/home/classes/wizard/logo-active.png'),
			},
			tanker: {
				backgroundActive: require('../../../assets/home/classes/tanker/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/tanker/logo-background-active.png'),
				logo: require('../../../assets/home/classes/tanker/logo.png'),
				logoActive: require('../../../assets/home/classes/tanker/logo-active.png'),
			},
			knight: {
				backgroundActive: require('../../../assets/home/classes/knight/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/knight/logo-background-active.png'),
				logo: require('../../../assets/home/classes/knight/logo.png'),
				logoActive: require('../../../assets/home/classes/knight/logo-active.png'),
			},
		},
	},
};
