export default {
	navigation: {
		bg: { uri: '/marketplace/navigation-bg.png' },
		logo: { uri: '/marketplace/flag.png' },
	},
	mint: {
		keyVisual: { uri: '/mint/key-visual.png' },
		cards: { uri: '/mint/cards.png' },
	},
	marketplace: {
		headingBackground: { uri: '/marketplace/heading-background.png' },
		mainBackground: { uri: '/marketplace/main-background.png' },
		underRealmInteractMaterial: {
			normal: {
				left: { uri: '/marketplace/under-realm-normal-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-normal-middle.png' },
				right: { uri: '/marketplace/under-realm-normal-right-edge.png' },
			},
			hover: {
				left: { uri: '/marketplace/under-realm-hover-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-hover-middle.png' },
				right: { uri: '/marketplace/under-realm-hover-right-edge.png' },
			},
		},
		card: {
			back: { uri: '/marketplace/under-realm-card-back.png' },
			front: { uri: '/marketplace/under-realm-card-front.png' },
		},
		mintBanner: { uri: '/marketplace/mint-banner.png' },
		coinUsd: { uri: '/marketplace/coin-usd.png' },
		mintWhyBuyNft: {
			edgeTopLeft: { uri: '/marketplace/mint-top-left-edge.png' },
			edgeTopRight: { uri: '/marketplace/mint-top-right-edge.png' },
			edgeBottomLeft: { uri: '/marketplace/mint-bottom-left-edge.png' },
			edgeBottomRight: { uri: '/marketplace/mint-bottom-right-edge.png' },
			borderTop: { uri: '/marketplace/mint-top-border.png' },
			borderBottom: { uri: '/marketplace/mint-bottom-border.png' },
			borderLeft: { uri: '/marketplace/mint-left-border.png' },
			borderRight: { uri: '/marketplace/mint-right-border.png' },
			background: { uri: '/marketplace/mint-bg.png' },
			bloodDrop: { uri: '/marketplace/icon-blood-drop.png' },
			patternTopLeft: { uri: '/marketplace/mint-top-left-pattern.png' },
			patternTopRight: { uri: '/marketplace/mint-top-right-pattern.png' },
			patternBottomLeft: { uri: '/marketplace/mint-bottom-left-pattern.png' },
			patternBottomRight: { uri: '/marketplace/mint-bottom-right-pattern.png' },
		},
		faq: {
			top: { uri: '/marketplace/faq-top.png' },
			middle: { uri: '/marketplace/faq-middle.png' },
			bottom: { uri: '/marketplace/faq-bottom.png' },
		},
		chevronDown: { uri: '/marketplace/chevron-down.png' },
		titleSeparator: { uri: '/marketplace/title-separator.png' },
		buyButtonBackground: { uri: '/marketplace/buy-button-bg.png' },
		buyButtonDash: { uri: '/marketplace/buy-button-inner-dash.png' },
		popupBorder: { uri: '/marketplace/popup-border.png' },
		popupBackground: { uri: '/marketplace/popup-bg.png' },
	},
	home: {
		headingBackground: { uri: '/home/heading-background.png' },
		cardsImage: { uri: '/home/cards-image.png' },
		battlefieldBackground: { uri: '/home/battlefield-background.png' },
		cardExplainBackground: { uri: '/home/card-explain-background.png' },
		cardExplain: { uri: '/home/card-explain.png' },
	},
};
