/* Generated by Metacraft devops toolchain,
 * do not edit this file! */

export default {
	region: 'ap-northeast-1',
	userPoolId: 'ap-northeast-1_6eSHOJnpy',
	userPoolWebClientId: '4piksftvktk2rrgv8e93gojdok',
	cognitoAuthDomain: 'login.stormgate.io',
	cognitoAuthScopes: [
		'aws.cognito.signin.user.admin',
		'email',
		'openid',
		'phone',
		'profile',
	],
};
